### PR TITLE
Moved HSS to past events and fixed layout in a less than ideal way

### PR DESCRIPTION
**Pull request by adrianleh**

### CODE REVIEW

**Comment by theRealSuperMario** [comment]
can we close / delte this? its not compatible anymore

**Comment by LeanderK** [comment]
I'll just close it. Yell and reopen if this is actually valid

**Comment by adrianleh** [comment]
Yelling!

**Comment by adrianleh** [comment]
There are some fixes in this, such as dates of events, which do definitely need to be merged

**Comment by LeanderK** [comment]
heard the yelling!

**Comment by LeanderK** [comment]
seems reasonable

**Pull request merged**
