### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by MaximilianFranz**
- moved hacksuchsoehne to past
- changed opencodes text to past form 
- added youtube link with button to opencodes banner

### CODE REVIEW

**Comment by theRealSuperMario** [comment]
the youtube link should also somehow be added to the past events gallery. Maybe create a subpage like for /deeplearning and then put information there.
People will not go to the about section to check out the event and they should see the aftermovie when they click on the event.

**Comment by theRealSuperMario** [comment]
official website link on och subpage links to youtube.
maybe add flickr gallery? https://flic.kr/s/aHsmdLB7AN

**Comment by theRealSuperMario** [comment]
flickr gallery link is not show. I think my web dev skills are not awesome enough to fix this.

**Comment by theRealSuperMario** [comment]
fixes #17.

I think we should merge and move on

**Comment by theRealSuperMario** [comment]
@LeanderK @adrianleh

**Comment by MaximilianFranz** [comment]
Looks good! Thanks for the edits :)

**Pull request merged**
