### PR TITLE
add learning-dexterity subpage and event-banner

### PR DESCRIPTION
**Pull request by MaximilianFranz**
Review Please

### CODE REVIEW

**Comment by MaximilianFranz** [comment]
@LeanderK @theRealSuperMario

**Comment by theRealSuperMario** [comment]
event link to ka-ai is missing
link to paper is missing
link to openai blog is missing

cooperation statement is missing

**Comment by MaximilianFranz** [comment]
What do you mean by 'cooperation statement'?

**Comment by theRealSuperMario** [comment]
I am on it

**Comment by MaximilianFranz** [comment]
Wait! Pushing fixes for everything else just now

**Comment by theRealSuperMario** [comment]
image

Just to make sure we have included all the information available

**Comment by MaximilianFranz** [comment]
Ok, if you've got all that ready I'll abandon mine..

**Comment by theRealSuperMario** [comment]
sorry @MaximilianFranz

**Pull request merged**
